spring:
  datasource:
#    druid:
#      url: jdbc:mysql://233.cc:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#      username: root
#      password: 123456
    url: jdbc:mysql://233.cc:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
#    host: 192.168.1.233 # Redis服务器地址
    host: 233.cc # Redis服务器地址
    database: 3 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.macro.mall: debug
